let data = [
  {
    "from": "Chennai",
    "to": "Bangalore",
    "date": "2026-06-14",
    "departureTime": "07:00 AM",
    "arrivalTime": "01:30 PM",
    "rating": 4.5,
    "price": 799,
    "name": "KPN Travels",
    "companyName": "KPN Transport Pvt Ltd",
    "buses": 12,
    "seats": 28
  },
  {
    "from": "Hyderabad",
    "to": "Vijayawada",
    "date": "2026-06-15",
    "departureTime": "09:30 PM",
    "arrivalTime": "04:15 AM",
    "rating": 4.2,
    "price": 650,
    "name": "APSRTC",
    "companyName": "Andhra Pradesh State Road Transport Corporation",
    "buses": 58,
    "seats": 792
  },
  {
    "from": "Mumbai",
    "to": "Pune",
    "date": "2026-06-16",
    "departureTime": "06:00 AM",
    "arrivalTime": "10:00 AM",
    "rating": 4.7,
    "price": 450,
    "name": "VRL Travels",
    "companyName": "VRL Logistics",
    "buses": 20,
    "seats": 45
  },
  {
    "from": "Delhi",
    "to": "Jaipur",
    "date": "2026-06-17",
    "departureTime": "10:15 PM",
    "arrivalTime": "05:00 AM",
    "rating": 4.1,
    "price": 950,
    "name": "Orange Travels",
    "companyName": "Orange Tours and Travels",
    "buses": 14,
    "seats": 30
  },
  {
    "from": "Chennai",
    "to": "Coimbatore",
    "date": "2026-06-18",
    "departureTime": "11:45 PM",
    "arrivalTime": "07:30 AM",
    "rating": 4.6,
    "price": 1200,
    "name": "Parveen Travels",
    "companyName": "Parveen Holidays Pvt Ltd",
    "buses": 18,
    "seats": 40
  },
  {
    "from": "Bangalore",
    "to": "Mysore",
    "date": "2026-06-19",
    "departureTime": "05:30 PM",
    "arrivalTime": "09:15 PM",
    "rating": 4.3,
    "price": 350,
    "name": "SRS Travels",
    "companyName": "SRS Transport",
    "buses": 10,
    "seats": 22
  },
  {
    "from": "Hyderabad",
    "to": "Chennai",
    "date": "2026-06-20",
    "departureTime": "08:15 PM",
    "arrivalTime": "07:45 AM",
    "rating": 4.4,
    "price": 999,
    "name": "TGSRTC",
    "companyName": "Telangana State Road Transport Corporation",
    "buses": 51,
    "seats": 1645
  },
  {
    "from": "Kochi",
    "to": "Trivandrum",
    "date": "2026-06-21",
    "departureTime": "07:20 AM",
    "arrivalTime": "01:40 PM",
    "rating": 4.0,
    "price": 450,
    "name": "YBM Travels",
    "companyName": "YBM Travels Pvt Ltd",
    "buses": 9,
    "seats": 19
  },
  {
    "from": "Madurai",
    "to": "Chennai",
    "date": "2026-06-22",
    "departureTime": "09:10 PM",
    "arrivalTime": "06:50 AM",
    "rating": 4.8,
    "price": 1350,
    "name": "Rathimeena Travels",
    "companyName": "Rathimeena Transport",
    "buses": 7,
    "seats": 15
  },
  {
    "from": "Visakhapatnam",
    "to": "Hyderabad",
    "date": "2026-06-23",
    "departureTime": "06:50 PM",
    "arrivalTime": "05:30 AM",
    "rating": 4.5,
    "price": 1100,
    "name": "National Travels",
    "companyName": "National Bus Services",
    "buses": 11,
    "seats": 26
  },
  {
    "from": "Chennai",
    "to": "Salem",
    "date": "2026-06-24",
    "departureTime": "08:40 AM",
    "arrivalTime": "02:45 PM",
    "rating": 4.2,
    "price": 550,
    "name": "Kallada Travels",
    "companyName": "Kallada Tours and Travels",
    "buses": 13,
    "seats": 34
  },
  {
    "from": "Bangalore",
    "to": "Chennai",
    "date": "2026-06-25",
    "departureTime": "10:00 PM",
    "arrivalTime": "05:45 AM",
    "rating": 4.6,
    "price": 899,
    "name": "SRM Travels",
    "companyName": "SRM Transport India",
    "buses": 16,
    "seats": 41
  },
  {
    "from": "Coimbatore",
    "to": "Madurai",
    "date": "2026-06-26",
    "departureTime": "06:30 AM",
    "arrivalTime": "11:00 AM",
    "rating": 4.1,
    "price": 420,
    "name": "Sharma Travels",
    "companyName": "Sharma Bus Lines",
    "buses": 8,
    "seats": 20
  },
  {
    "from": "Hyderabad",
    "to": "Bangalore",
    "date": "2026-06-27",
    "departureTime": "09:45 PM",
    "arrivalTime": "08:15 AM",
    "rating": 4.7,
    "price": 1450,
    "name": "GreenLine Travels",
    "companyName": "GreenLine Mobility",
    "buses": 22,
    "seats": 55
  },
  {
    "from": "Goa",
    "to": "Bangalore",
    "date": "2026-06-28",
    "departureTime": "09:00 PM",
    "arrivalTime": "06:40 AM",
    "rating": 4.4,
    "price": 1299,
    "name": "SeaBird Travels",
    "companyName": "SeaBird Tourist",
    "buses": 11,
    "seats": 29
  }
]
  

module.exports = {data:data};